version: 2
updates:
  # Surveiller les dépendances NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/Xtraktor"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/Xtraktor.Tests"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  # Surveiller les mises à jour des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
